-- Copied from pgAdmin

-- Database: followtracker

-- DROP DATABASE followtracker;

CREATE DATABASE followtracker
    WITH 
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.UTF-8'
    LC_CTYPE = 'en_US.UTF-8'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

GRANT ALL ON DATABASE followtracker TO postgres;

GRANT TEMPORARY, CONNECT ON DATABASE followtracker TO PUBLIC;

GRANT ALL ON DATABASE followtracker TO followtracker_rw;